on:
  workflow_dispatch:

jobs:
  build:
    name: build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1.0.13

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build
      run:
        xmake -w

    - name: Merge Qt Stuff
      run:
        xmake install -o buildMerged

    - name: Remove Uneccesary Qt Stuff 1
      if: matrix.os == 'windows-latest'
      uses: JesseTG/rm@v1.0.0
      with:
        path: buildMerged\\bin\\vc_redist.x64.exe

    - name: Remove Uneccesary Qt Stuff 2
      if: matrix.os == 'windows-latest'
      uses: JesseTG/rm@v1.0.0
      with:
        path: buildMerged\\bin\\opengl32sw.dll

    - name: Zip Windows Release
      if: matrix.os == 'windows-latest'
      uses: vimtor/action-zip@v1
      with:
        files: buildMerged\\bin
        recursive: true
        dest: buildZipped\\EasyAutoTracker-Windows.zip

    - name: Zip Linux Release
      if: matrix.os == 'ubuntu-latest'
      uses: vimtor/action-zip@v1
      with:
        files: buildMerged\\bin
        recursive: true
        dest: buildZipped\\EasyAutoTracker-Linux.zip

    - name: Create draft Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        name: v0.0.0 NEW DRAFT RELEASE
        generate_release_notes: true
        files: |
          buildZipped\\EasyAutoTracker-Windows.zip
          buildZipped\\EasyAutoTracker-Linux.zip

