on:
  workflow_dispatch:

jobs:
  build:
    name: build on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2022]
#TODO: Figure out how to get a newer clang version installed, then re-add linux:    os: [ubuntu-latest, windows-latest]

    steps:
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1.0.13
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Build
      run:
        xmake -w
    - name: Merge Qt Stuff
      run:
        xmake install buildMerged
    - name: Remove Uneccesary Qt Stuff 1
      uses: JesseTG/rm@v1.0.0
      with:
        path: buildMerged\bin\vc_redist.x64.exe
    - name: Remove Uneccesary Qt Stuff 2
      uses: JesseTG/rm@v1.0.0
      with:
        path: buildMerged\bin\opengl32sw.dll
